First commit
styleru/Mik-Oil pull request #8
Opened 2020-02-18 15:16 UTC by VyachAndreev

eh

2020-02-22 14:34 UTC, Yundin requested changes
Нормас, но нейминг всё портит

2020-02-22 14:34 UTC, Yundin commented on app/build.gradle
> +    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.0'
Зависимости надо подписывать, чтобы не получилось каши. А ты зачем-то ещё и мои комменты стёр

2020-02-22 14:34 UTC, Yundin commented on app/src/main/AndroidManifest.xml
> +    package="com.andreev.bvsru">
PackageName менять нельзя

2020-02-22 14:34 UTC, Yundin commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="org.styleru.mik_oil.MainActivity">
Отголоски смены packageName, такого быть не должно

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/MainActivity.java
> +                    .add(R.id.fragment_container, fragment)
add почти всегда плохая идея, тут лучше использовать replace

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/MainActivity.java
> +    public FragmentManager fm;
Эта переменная используется дважды, а потом создаётся точно такая же, но на один символ короче. Ты уверен, что она тут нужна?

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/MainActivity.java
> +    public void goToScreen1(){
Из названия непонятно, куда именно мы переходим

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/MainActivity.java
> +        }else{
В каком случае мы попадём в этот else? Мне кажется, что никогда

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/MainActivity.java
> +    public void goToScreen1(){
Ставь пробел перед `{`

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/MainActivity.java
> +        }else{
Не прилепляй скобки к чему-то еще, пиши `} else {`

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/MainActivity.java
> +                    .commit();
У тебя два блока текста делают одно и то же: отображают Screen1. Может, можно оставить только один?

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen1.java
> +public class Screen1 extends Fragment {
Из названия класса непонятно, что это за экран, что он делает, это фрагмент или активити?

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen1.java
> +    Button entButton;
ent – для меня неочевидное соращение

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen1.java
> +    interface Screen1Int{
Из название я интерфейса непонятно, что за интерфейс

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen1.java
> +        void goToScreen1();
Из названия метода непонятно, куда перемещаемся

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen1.java
> +        ButterKnife.bind(this, v);
ButterKnife::bind должен быть в onViewCreated

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +public class Screen2 extends MvpAppCompatFragment implements Screen2View {
Из названия класса непонятно, что это за экран, что он делает, это фрагмент или активити?

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    Button Sc2GoBtn;
Имена переменных должны быть в camelCase

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    ProgressBar PB;
Имена переменных должны быть в camelCase

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    TextView resView;
res – сокращение для result или resource. Не каждое слово стоит сокращать.

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    EditText pasEditText;
Сокращение для пароля – pass

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    EditText logEditText;
Поле для ввода логов? Логин не сокращается

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    interface Screen2Int{
Из названия интерфейса ничего не понятно

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +        void goToScreen2();
Из названия интерфейса ничего не понятно

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    public void Return() {
Имена методов должны быть в camelCase

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    }
Зачем нам возвращаться на прошлый экран?

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    public void Progress(boolean isGoing) {
Имена методов должны быть в camelCase

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2Presenter.java
> +            getViewState().Progress(false);
Приложение упадёт, если sendRequest будет вызван не из главного потока

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2Presenter.java
> +            getViewState().Return();
В тз нет ничего про возвращение на предыдущий экран. Зачем нам такое поведение? Здесь должен быть переход на main, которого пока нет, при успехе и тост с ошибкой при неудаче

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2Presenter.java
> +            return "Whyever don't ya enter anything?"; // Make this work with string.xml
Строки должны быть в ресурсах

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2Presenter.java
> +            return "Not today, bro(, work is still in progress"; // Make this work with string.xml
Строки должны быть в ресурсах

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2Presenter.java
> +        return "Maybe you should REMEMBER ALL YOUR PASSSWORDS???"; // Make this work with string.xml
Строки должны быть в ресурсах

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2Presenter.java
> +    private String toastString(String login, String password){
Название метода не говорит о том, что он делает какие-то проверки, а он почему-то делает

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2Presenter.java
> +    private String toastString(String login, String password){
А проверку на валидность и генерацию числа, имитирующую запрос на сервер, неплохо бы разнести по 2 разным методам

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2View.java
> +    void Progress(boolean isGoing);
`progress`

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2View.java
> +    void Return();
`return`

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    }
И почему метод return не возвращает нас на прошлый экран, а кидает на первый, причём создавая его заново?

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +    }
(прошлый экран может быть не Screen1)

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/action_bar_layout.xml
> +<TableLayout
Почему именно TableLayout?

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +<?xml version="1.0" encoding="utf-8"?>
Имя ресурса должно быть с snake_case

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        android:layout_width="270sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        android:layout_width="270sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        android:padding="10sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        android:padding="10sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:layout_width="270sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:padding="10sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:layout_width="270sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:padding="10sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:padding="10sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:layout_width="180sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:padding="10sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/Screen2.java
> +        }
А сделать кнопку снова видимой?

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/action_bar_layout.xml
> +            android:padding="10sp"
В sp указывается размер текста, остальное в dp

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +    android:orientation="vertical" android:layout_width="match_parent"
Для ConstraintLayout ориентация не требуется

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        android:id="@+id/regButton"
id должны быть в snake_case

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        android:id="@+id/entButton"
id должны быть в snake_case

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        android:id="@+id/entButton"
Здесь не стоит сокращать enter

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:id="@+id/logEditText"
id должны быть в snake_case

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:id="@+id/pasEditText"
id должны быть в snake_case

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:id="@+id/pasEditText"
Пароль сокращается как pass

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:id="@+id/Sc2GoBtn"
id должны быть в snake_case

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:id="@+id/PBSc2"
id должны быть в snake_case

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/values/strings.xml
> +    <string name="TextForToast">Not today, bro(</string>
id должны быть в snake_case

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        app:layout_constraintRight_toRightOf="parent"
Вместо Left/Right стоит использовать Start/End, писать и то и то нет смысла

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        app:layout_constraintVertical_chainStyle="spread" />
У тебя в вёрстке нет никакого chain

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        app:layout_constraintHorizontal_bias="0.522"
А почему бы не сместить кнопку на пару пикселей вправо?

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:id="@+id/reset"
Кнопка совсем не похожа на ту, что в дизайне: другой шрифт, другой цвет, другой размер, другое расположение

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        android:id="@+id/regButton"
Шрифты на всех кнопках не такие, как в дизайне

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:id="@+id/PBSc2"
А ещё должны нести смысл

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:textAllCaps="false"
А в дизайне она капсом

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        app:layout_constraintStart_toStartOf="@+id/pasEditText"
Зачем привязывать к текстовому полю, оно может уехать. Привяжи к краям экрана

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen2.xml
> +        android:layout_width="180sp"
И в дизайне 120

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/values/styles.xml
> +        <item name="contentInsetEnd">0dp</item>
Если это костыль для чего-то, подпиши, для чего именно

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/values/styles.xml
> +        <item name="android:background">#FFCC33</item>
В дизайне bg другого цвета

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        app:layout_constraintHorizontal_bias="0.5"
bias со значением 0.5 бесполезен, это default

2020-02-22 14:34 UTC, Yundin commented on app/src/main/res/layout/screen1.xml
> +        android:id="@+id/entButton"
Неплохо бы сделать тень, как в дизайне

2020-02-22 14:36 UTC, Yundin commented
Ой, ещё с коммитами беда: почему их всего 2? По объёму там минимум 6. Почему в сообщении к коммиту не написано ничего осмысленного?

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/java/org/styleru/mik_oil/HomeFragment.java
> +        ButterKnife.bind(this, v);
ButterKnife.bind() следует поместить в OnViewCreated()

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/java/org/styleru/mik_oil/LoginFragmentPresenter.java
> +    }
Некрасивые пустые строчки

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="56dp"
Не стоит хардкодить высоту текстовых полей

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/home_fragment.xml
> +        android:layout_height="48dp"
Хардкод ширины и высоты

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/home_fragment.xml
> +        android:layout_marginBottom="446dp"
Лучше попробовать обойтись без этих отступов

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/home_fragment.xml
> +        android:layout_width="270dp"
Хардкод ширины и высоты

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/home_fragment.xml
> +        app:layout_constraintVertical_bias="0.118" />
Этот атрибут точно необходим?

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/login_fragment.xml
> +        android:layout_marginBottom="446dp"
Хардкод ширины и высоты, отступы лучше убрать и использовать цепи

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/login_fragment.xml
> +        android:layout_marginBottom="376dp"
Хардкод ширины и высоты, отступы лучше убрать

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Почему привязка к родителю? Разумнее привязаться к предыдущему EditText, тогда и отступы не нужны

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/home_fragment.xml
> +        app:layout_constraintTop_toTopOf="parent"
Привяжись к предыдущей кнопке

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/login_fragment.xml
> +        android:layout_marginEnd="45dp"
Без них ведь можно обойтись?

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Привязка к родителю, неадаптивность верстки

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/login_fragment.xml
> +        android:layout_height="48dp"
Хардкод ширины и высоты

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintTop_toTopOf="parent"
Отступы, привязка к родителю вместо предыдущего TextView

2020-02-26 05:35 UTC, Savely-Prokhorov commented on app/src/main/res/values/font_certs.xml
> +    </string-array>
Страшно

2020-02-26 19:52 UTC, Asideron commented on app/src/main/java/org/styleru/mik_oil/LoginFragmentPresenter.java
> +    }
А так ли это критично?
Мне кажется, в данном случае, это дело стиля или желания разграничить блоки кода более явно.
Мсье Влад, мы нуждаемся в вашем мнении по данному вопросу(опросу)!

2020-02-26 20:32 UTC, Fliolli commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/textView"
Название вьюшки ни о чем не говорит

2020-02-26 20:32 UTC, Fliolli commented on app/src/main/res/layout/activity_main.xml
>          android:layout_height="wrap_content"
Лучше использовать ?attr/actionBarSize для определения высоты тулбара

2020-02-26 20:32 UTC, Fliolli commented on app/src/main/res/layout/fragment_login.xml
> +        android:layout_height="75dp"
Можно заменить на "wrap_content"

2020-02-26 20:32 UTC, Fliolli commented on app/src/main/java/org/styleru/mik_oil/LoginFragmentPresenter.java
> +        if (login.equals("") || password.equals("")){
Можно применить метод isEmpty()

2020-02-26 21:14 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragmentPresenter.java
> +    }
@Asideron Я тоже люблю разделять блоки пустыми строчками, имхо это нормально выглядит, но если удалить 15 и 20 строки, то всё еще будет норм. И призывайте меня по нику, я могу что-то пропустить

2020-02-29 14:12 UTC, closed without merging