prokhorov
styleru/Mik-Oil pull request #9
Opened 2020-02-21 15:20 UTC by Savely-Prokhorov

2020-02-22 15:59 UTC, Yundin requested changes
Довольно аккуратно написано, но страдают правила написания имён

2020-02-22 15:59 UTC, Yundin commented on .idea/codeStyles/Project.xml
> -      <option name="ARRANGEMENT_SETTINGS_MIGRATED_TO_191" value="true" />
Попробуй обновить студию, мб это пропадёт

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/EntranceFragment.java
> +    //Entrance Fragment
Комментарий лишний

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/EntranceFragment.java
> +    Button EnterButton;
Имена переменных должны быть в camelCase

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/EntranceFragment.java
> +//        setRetainInstance(true);  redundant, doesn't work with backstack
Раз это не нужно – удали. И весь onCreate здесь ничего не делает

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/EntranceFragment.java
> +        ButterKnife.bind(this, view);
ButterKnife::bind должен вызываться в onViewCreated

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/EntranceFragment.java
> +    //Entrance Fragment
Комментарий лишний

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +    Button GoButton;
Имена переменных должны быть в camelCase

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +    }
Метод не несёт смысловой нагрузки

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +        RecoveryLink.setPaintFlags(RecoveryLink.getPaintFlags() | Paint.UNDERLINE_TEXT_FLAG);
Эти вещи должны выполняться в onViewCreated

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +        //underline recovery button
Вот к таким вещам нужны комменты, тут он очень в тему

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +    }
В этом месте всё очень странно.

1. View не должна ничего имитировать. Чтобы сымитировать какую-то деятельность, нужно уметь это делать, а View как раз ничего не должна уметь, тем более запросы. Она только делает то, что говорит ей делать презентер. Следовательно, и имитировать запрос должен он, а для View разницы между запросом фейковым и настоящим быть не должно.
2. `imitateRequest` вызывается из презентера. И единственной строчкой мы дёргаем презентер... Почему презентер напрямую не вызвал свой `showProgressBar`?
3. Если у презентера и будет метод `showProgressBar`, то он будет приватным, потому что никто не должен ему указвать, что делать. View только уведомляет его о действиях пользователя, дальше он сам.

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +                imitateRequest();
Здесь мы должны сразу сообщить презентеру о том, что кнопка была нажата. Именно о событии нажатия и не более того

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +        });
Не понимаю, с какой целью это используется

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +    public void changeVisibility(boolean isVisible){
visibility чего?

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +            activity.runOnUiThread(new Runnable() {
Такими штуками можно не заморачиваться. Если презентер вызвал метод из неправильного потока – это его вина

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +        circularProgressBar.setProgress(++progress);
Зачем мы увеличиваем прогресс? У нас же нет никакого бара, прогресс по умолчанию `indeterminate`, то есть он просто крутится, не считывая значения

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        android:indeterminate="false"
А, ты ставил indeterminate="false". Но этого недостаточно, чтобы сделать его детерменированным, а нам это и не нужно. Но если интересно, читай [документацию](https://developer.android.com/reference/android/widget/ProgressBar).

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +            activity.runOnUiThread(new Runnable() {
Лишнее

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +    public void showToast(String toast_text){
Имена параметров метода должны быть в camelCase

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +                    toast.setGravity(Gravity.BOTTOM, 0, 50);
Не понимаю, зачем это

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +        closeFragment();
Почему каждый раз показывая тост, мы закрываем фрагмент?

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +    }
Это не закрытие текущего фрагмента, это переход на EntranceFragment

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +    //Login Fragment
Необязательный комментарий

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginPresenter.java
> +//    }
Никогда не стоит коммитить закомментированный код. Вообще комментирование кода – bad practice.

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginPresenter.java
> +        String toast_text = state ? "Success!" : "Failed!";
Строки должны быть в ресурсах

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginPresenter.java
> +        String toast_text = state ? "Success!" : "Failed!";
А имена переменных должны быть в camelCase

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginPresenter.java
> +                            getViewState().increaseProgress();
Идея понятна, но

1. Нам сейчас не нужно такое поведение
2. У презентера и вью разные счётчики и их согласованность никто не гарантирует

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginPresenter.java
> +                            getViewState().increaseProgress();
Если презентер создастся не в главном потоке, приложение здесь упадёт

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginView.java
> +    void increaseProgress();
После переворота счётчик обнулится и `increaseProgress` вызовется не больше одного раза, получится неконсистентность между счётчиками view и presenter

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginView.java
> +    void showToast(String toast_text);
Имена параметров метода должны быть в camelCase

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginView.java
> +    void imitateRequest();
Этот метод очень не mvp'шный. Описывал выше, почему

2020-02-22 15:59 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginView.java
> +    void imitateRequest();
Он ещё и презентером не вызывается

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
В файлах ресурсов имена перевёрнуты относительно имён классов. То есть LoginFragment – fragment_login, TwoDotsActivity – activity_two_dots

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +        android:id="@+id/RegisterButton"
id должны быть в snake_case

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +        android:id="@+id/EnterButton"
id должны быть в snake_case

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        android:id="@+id/LoginEditText"
id должны быть в snake_case

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        android:id="@+id/PasswordEditText"
id должны быть в snake_case

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        android:id="@+id/RecoveryLink"
id должны быть в snake_case

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        android:id="@+id/GoButton"
id должны быть в snake_case

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        android:id="@+id/ProgressBar"
id должны быть в snake_case

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/toolbar.xml
> +    android:id="@+id/myTitle"
id должны быть в snake_case

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +    android:id="@+id/EntranceFragment"
id должны быть в snake_case

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +        android:layout_height="48dp"
Нельзя хардкодить и высоту и ширину на полях с тестом, иначе при увеличении текста всё обрежется
<img width="288" alt="Снимок экрана 2020-02-22 в 18 25 14" src="https://user-images.githubusercontent.com/24312750/75094918-ab94b780-55a0-11ea-89ee-ab444718fe2b.png">

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +        android:id="@+id/RegisterButton"
Все кнопки выглядят не так, как в дизайне

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +        app:layout_constraintRight_toRightOf="parent"
Вместо Left/Right стоит использовать Start/End

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +        app:layout_constraintVertical_chainStyle="packed"
Здесь цепь не очень нужна, а в таком виде она вообще не выполняет никаких функций

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +        android:layout_height="48dp"
Хардкод ширины и высоты

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +        app:layout_constraintRight_toRightOf="parent"
Start/End

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +<!---->
Лишний комментарий

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        android:layout_height="48dp"
Захардкоженные ширина и высота

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintVertical_chainStyle="packed" />
chainStyle стоит указывать только один раз на самой левой/верхней вью

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintRight_toRightOf="@id/PasswordEditText"
End

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintVertical_chainStyle="packed" />
chainStyle стоит указывать только один раз на самой левой/верхней вью

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintVertical_chainStyle="spread" />
Эта вью не находится ни в одной цепи

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintVertical_chainStyle="spread" />
Эта вью не находится ни в одной цепи

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/toolbar.xml
> +    android:layout_height="fill_parent"
fill_parent – это устаревший match_parent, никто им уже не пользуется

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">Muller</item>
Смена шрифта так не работает

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/values/styles.xml
> +    <style name="EditTextTheme" parent="Widget.AppCompat.EditText">
Это всё таки стиль, а не тема

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/values/strings.xml
> +    <string name="go_string">Go</string>
Не обязательно приписывать `_string` к каждой строке. Лучше напиши, в каком контексте это будет применяться. `go_button`, `login_hint`, ...

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintRight_toRightOf="parent"
Start/End

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        android:radius="10dp"
У кнопки нет такого аттрибута

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintRight_toRightOf="parent"
Start/End

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        android:layout_marginTop="22dp"
Зачем этот отступ? Из-за него кнопка и прогресс находятся в разных местах

2020-02-22 15:59 UTC, Yundin commented on app/src/main/res/layout/login_fragment.xml
> +        app:layout_constraintTop_toBottomOf="@+id/RecoveryLink"
Почему не привязать прогресс к кнопке? Вдруг её придётся двигать

2020-02-22 19:44 UTC, Savely-Prokhorov commented on app/src/main/java/org/styleru/mik_oil/EntranceFragment.java
> +//        setRetainInstance(true);  redundant, doesn't work with backstack
Оставил исключительно для себя в образовательных целях. Понятно, что в проект такой коммент попасть не должен

2020-02-22 19:47 UTC, Savely-Prokhorov commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +        });
Да, эта штука действительно не работает так, как я хотел (чтобы после ввода данных курсор не мигал). Стоило этот код удалить

2020-02-22 19:49 UTC, Savely-Prokhorov commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +                    toast.setGravity(Gravity.BOTTOM, 0, 50);
Отображаем Toast внизу экрана

2020-02-22 19:51 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginFragment.java
> +                    toast.setGravity(Gravity.BOTTOM, 0, 50);
Он по умолчанию отображается внизу экрана, без `setGravity`

2020-02-22 19:51 UTC, Savely-Prokhorov commented on app/src/main/java/org/styleru/mik_oil/LoginPresenter.java
> +//    }
Разумеется. Плохо причесал код перед коммитом. А если не комментировать, то что с ним делать? Новый коммит, чтоб потом можно было откатиться?

2020-02-22 19:52 UTC, Yundin commented on app/src/main/java/org/styleru/mik_oil/LoginPresenter.java
> +//    }
Да, делать достаточно частые коммиты, чтобы захватывать все версии кода

2020-02-22 19:54 UTC, Savely-Prokhorov commented on app/src/main/res/layout/entrance_fragment.xml
> +        android:layout_height="48dp"
Пытался соответствовать дизайну

2020-02-23 12:41 UTC, Yundin commented on app/src/main/res/layout/entrance_fragment.xml
> +        android:layout_height="48dp"
Соответствовать дизайну можно (и нужно) без хардкода высоты

2020-02-29 14:12 UTC, closed without merging